version: 2
jobs:
  build:
    docker:
      - image: ruby:2.3
    working_directory: ~/oauth2-provider
    steps:
      - checkout
      - run:
          name: Install Ruby Bundler gem
          command: gem install bundler --no-doc
      - run:
          name: Install Ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Install Ruby Appraisal dependencies
          command: bundle exec appraisal install
      - run:
          name: Run tests
          command: bundle exec appraisal rake spec
